version: '3'

services:
  web:
    image: question-answers
    tty: true
    stdin_open: true
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
        - .:/app:delegated
    env_file:
      - .env
    entrypoint: ["./web_entrypoint.sh"]
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]

  postgres:
    image: postgres:9.6.3-alpine
    volumes:
      - ./tmp/postgres/data:/var/lib/postgresql/data:delegated
